### ISSUE TITLE
RTL simulation on pulp

### ISSUE THREAD

**Issue by yswntht** [pulp-platform/pulp-dsp#55]
Hi,

I see the current support for pulp-dsp is for Mr.Wolf and GVSOC platform. instead of GVSOC can the pulp RTL (https://github.com/pulp-platform/pulp) be used to simulate this? does it require additional configuration/changes to support this?

Thanks.

**Comment by xiaywang** [comment]
Hi,

yes, the kernels of the library (in the folders called 'kernels') should work also with the configs pulp.sh and platform-rtl.sh. We tested the dot prod function and it worked successfully. While the glue codes are more specific for Mr. wolf, you might need to adapt them for other pulp SoCs.

Best,
Xia
