### ISSUE TITLE
Makefile not implemented for lib build

### ISSUE THREAD

**Issue by ghost** [pulp-platform/pulp-dsp#59]
Hi, 

You mention "make clean  header all install" to build and install the lib.
Current makefile only compile the doc...
Any things we need to know to use the code as lib? 
Regards,
O.C

**Comment by xiaywang** [comment]
Hi,
I cannot reproduce your error. I've rebuilt the library by simply doing 'make clean header all install' and it works as expected.
For which pulp platform are you trying to build the library?
Best,
Xia

**Comment by ghost** [comment]
Hi, 
Thank you for your reply.
The issue comes from my environment (specific pulp sdk flavor).
Regards,
O.C
