### ISSUE TITLE
Gapuino support

### ISSUE THREAD

**Issue by MiguelCosta94** [pulp-platform/pulp-dsp#60]
Hi,

Is it possible to use PULP-DSP in Gapuino?

**Comment by xiaywang** [comment]
Hi,

we are currently working on it. I will notify you here once it's ready.

Best,
Xia

**Comment by xiaywang** [comment]
Hi,
we added support to the pmsis interface, which is used in gap-sdk. The kernels functions should run on gap too.
Best,
Xia
